#!/bin/sh
# File generated by ocamlbuild

cd /home/majid/Bureau/TP5/TP5/Ocaml-

rm -f ART.cmo
rm -f CLL.cmo
rm -f CLLInstr.cmo
rm -f CLLtoIMP.cmo
rm -f FUN.cmo
rm -f FUNInstr.cmo
rm -f FUNtoCLL.cmo
rm -f IMP.cmo
rm -f IMPExpr.cmo
rm -f IMPInstr.cmo
rm -f Op.cmo
rm -f VAR.cmo
rm -f VARCompiler.cmo
rm -f VARLexer.cmo
rm -f VARParser.cmo
rm -f VARtoFUN.cmo
# Also clean the script itself
rm -f /home/majid/Bureau/TP5/TP5/Ocaml-/_build/sanitize.sh
